version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: hacker-news-app
    restart: always
    build: .
    ports:
      - 8080:8080
    command: --spring.profiles.active=docker
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hacker_news_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root

