version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: hacker-news-app
    restart: always
    build: .
    ports:
      - 8080:8080
    command: --spring.profiles.active=docker
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: prajyot
      MYSQL_PASSWORD: prajyot
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb2
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hacker_news_db
      MYSQL_USER: prajyot
      MYSQL_PASSWORD: prajyot
      MYSQL_ROOT_PASSWORD: prajyot

